@startuml

    object App
    object scanner

    object parser

    object analyzer

    object token

    object symbolTable

    object error

    object syntaxTree

    object goalsScanner

    object readFile
    object closeFile
    object manageLexicalErrors
    object verifyRegularGrammar
    object getToken
    object isEndOfFile
    object createSymbolTable
    object ignoreComments

    object verifyContextFreeGrammar
    object generateSyntaxTree
    object manageSyntaxErrors
    object verifyCompleteFile
    object hasErrors

    object goalParser

    App ..> analyzer

    analyzer *-- scanner
     parser ..> token
    scanner ..> token


    scanner .up.> error
    parser .up.> error

    parser o-right- scanner: getToken

    scanner ..> syntaxTree

    scanner ..> symbolTable
    parser ..>  symbolTable



    scanner *-right- goalsScanner

    parser *-left- goalParser


    goalParser <|-up- readFile
    goalParser <|-up- closeFile
    goalParser <|-up- manageLexicalErrors
    goalParser <|-left- verifyRegularGrammar
    goalParser <|-down- getToken
    goalParser <|-down- isEndOfFile
    goalParser <|-down- createSymbolTable
    goalParser <|-down- ignoreComments

    goalsScanner <|-right- verifyContextFreeGrammar
    goalsScanner <|-down- generateSyntaxTree
    goalsScanner <|-down- manageSyntaxErrors
    goalsScanner <|-up- verifyCompleteFile
    goalsScanner <|-up- hasErrors


@enduml