@startuml parserclassdiagram



package analyzer{

    package controller{

    
        class ErrorController{
            -Error error

        } 


    
        package parser{

            enum ParserFactory{
                +getParser(): Parseable
            }

            interface Parseable{
                +getToken(): Token
                +isEndOfFile(): boolean
                +readFile():boolean
            }

            package jssparsercontroller{
                class JSSParser{
                    -TransitionFunctionController transitionFunction
                    -int line
                    -int column
                    -String path
                    -String content
                }

                class AccecptanceStatesController{
                    +getAcceptanceState(State state):TypeToken
                }

                class TransitionFunctionController{
                    -State[][] statesMatrix
                    +delta(State state, AlphabetSymbol symbol): State
                }

                class AlphabetSymbolController{
                    +isCharacterTerminator(): boolean
                    +getAlphabetSymbol(char test): AlphabetSymbol
                }

                JSSParser *-- TransitionFunctionController
                JSSParser --> AccecptanceStatesController
                JSSParser --> AlphabetSymbolController

            }

            
            ParserFactory .left.> Parseable

            JSSParser -up-|> Parseable
            

        }



        

        
        Scannable -right-> Parseable: getToken

    }


    package model{


        class Token{
            -TypeToken typeToken
            -int line
            -int column 
            -String path
        }

        enum TypeToken{

        }

        package jssparser{
            enum State{
                +ST0
                +ST1
            }

            class AccecptanceStates{
                -List<State> acceptanceStates
                +getAcceptanceStates(): List<State>
            }

            

            enum AlphabetSymbol{
                +DIGIT
                +LETTER
            }
        }

        Token *-- TypeToken

    }

    

    

    Parseable ..> Token
    AccecptanceStatesController --> AccecptanceStates
    AccecptanceStatesController ..> TypeToken
    TransitionFunctionController *-- State
    TransitionFunctionController ..> AlphabetSymbol
    AlphabetSymbolController ..> AlphabetSymbol
}

package utils{
        class ManageFiles{
            +String readTextFile(String path): String
        }
    }


Parseable ..> ManageFiles

@enduml