@startuml resume

    object App

    object scanner

    object parser

    object analyzer

    object token

    object symbolTable

    object error

    object syntaxTree

    object goalsScanner

    object goalParser

    App ..> analyzer

    parser ..> token
    scanner ..> token


    analyzer *-- scanner
    

    scanner .up.> error
    parser .up.> error

    parser o-right- scanner: getToken

    scanner ..> syntaxTree

    scanner ..> symbolTable
    parser ..>  symbolTable

    

    scanner *-right- goalsScanner

    parser *-left- goalParser


   


@enduml